### ISSUE TITLE
Created point features not clickable

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1124] opened 2021-02-03 09:45 UTC
Bug reproduced on both Android and iOS

Reproduce:
- Open project `lutraconsulting/nearest-vr`
- Digitize more than two point features
- Try to select and deselect some features

App might even crash during creation of new features.
Point markers are even not visible from time to time

Project `lutraconsulting/nearest-vr` contains harder filter expression for value relation, maybe that can point us somewhere.

Issue probably related to #1035

**Comment by tomasMizera** [comment] 2021-02-03 13:47
Reproducible even on desktop Linux. Interesting fact - if you zoom out almost to maximum, it is possible to select these features, on the other hand, when you zoom in, features disappear

**Comment by sklencar** [comment] 2021-02-04 10:18
The same issue occur in QGIS (3.14.15)

**Comment by saberraz** [comment] 2021-06-01 09:19
@sklencar does your PR close this too?

**Comment by jozef-budac** [comment] 2021-11-10 07:53
It still crashes on the latest 1.1.0 INPUT version

**Comment by tomasMizera** [comment] 2021-11-10 08:18
Let's see if new QGIS core will fix this.

**Comment by PeterPetrik** [comment] 2022-01-21 11:41
@jozef-budac can you please try with Input 1.2.0 which has QGIS 3.22 if still an issue?

**Comment by jozef-budac** [comment] 2022-01-28 07:54
The behavior is little bit different but the bug remains.
I was not able to simulate the crash anymore. 
But still there are two problems:
1) points are visible only when zoom out almost to maximum
2) points are not clickable

**Comment by wonder-sk** [comment] 2022-02-03 13:32
It looks like the problem is that the `gpkg_contents` meta-table has null extent set for the "hydrants" layer, which in turn gives empty extent in QgsVectorLayer, and that explains why things like identify do not work correctly or that the layer is not always getting rendered:

```
sqlite> select * from gpkg_contents;
table_name  data_type   identifier  description  last_change               min_x             min_y            max_x             max_y             srs_id    
----------  ----------  ----------  -----------  ------------------------  ----------------  ---------------  ----------------  ----------------  ----------
streets     features    streets                  2021-02-02T15:48:30.545Z  17.0955066680908  48.092845916748  17.1975898742676  48.1704711914062  4326      
hydrants    features    hydrants                 2021-05-26T08:58:34.341Z                                                                         4326      
```
No idea though why the extent is empty or how it has happened. Maybe a check in Mergin QGIS plugin could help to avoid this issue in future - but it seems to be quite rare...

**Comment by PeterPetrik** [comment] 2022-02-03 14:11
could it be in any means some weirdo geodiff problem. like switching off sqlite/geopackage triggers when adding a points to empty layer?

**Comment by wonder-sk** [comment] 2022-02-03 14:33
> could it be in any means some weirdo geodiff problem. like switching off sqlite/geopackage triggers when adding a points to empty layer?

That shouldn't be the case - those things are being done all the time and other projects don't suffer from it.

In this particular project, the extent in gpkg_contents got nulled in v3 uploaded from mergin plugin, and geodiff was not involved in the push of the data (it was a full upload of the gpkg).

**Comment by PeterPetrik** [comment] 2023-10-05 14:02
crash is not reproducible anymore and the issue should be fixed by validator in mergin-plugin (it is rare and likely corrupted file)

**Closed by PeterPetrik** 2023-10-05 14:02 UTC
Labels: bug, qgis, data corruption - sync failure - crash, blocked upstream
