### ISSUE TITLE
Support for external receiver via NMEA over TCP

### ISSUE THREAD

**Issue by pyrog** [MerginMaps/input#2332] opened 2022-10-21 08:56 UTC
Some GNSS receivers could send a NMEA stream over TCP (port 1958 by default).
The receiver could be a client of your app (MerginMaps is the TCP server)…
or the server (MerginMaps is the client).

### Softwares
- [Vespucci](https://vespucci.io/help/en/GPS%20sources/) an OpenStreetMap editor

### GNSS receivers
- [Sparkfun RTK devices](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/309)
- [Emlid Reach M2](https://docs.emlid.com/reach/reachview-3/settings-overview/#position-streaming)

**Comment by wonder-sk** [comment] 2022-10-21 09:26
Duplicate of #1893

**Closed by wonder-sk** 2022-10-21 09:26 UTC
Labels: GPS
