### ISSUE TITLE
The app takes ages to load when there are several downloaded local projects

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2800] opened 2023-09-25 13:03 UTC
with unsynced changes.

To replicate:
1- Download tens of projects (maybe 6-7 will do)
2- Make some changes to the projects
3- **Do NOT SYNC your changes**
4- Close the app by swiping
5-  Re-open the app

It will take a long time to see the Home page of the app.

**Comment by tomasMizera** [comment] 2023-09-25 13:09
Duplicate of #1556

**Closed by tomasMizera** 2023-09-25 13:09 UTC
Labels: performance
