### ISSUE TITLE
Fully zooming in while recording polygons crashes Input 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2142] opened 2022-06-29 12:40 UTC
Start recording polygons, place a few points and start zooming in, at about 10 - 100 meters, the input will crash without an error message. 

Both Android and iOS

**Comment by roya0045** [comment] 2022-08-10 12:40
Cannot reproduce on iOS15.6 with Mergin 1.6.0.

**Comment by tomasMizera** [comment] 2023-10-26 07:49
Seems to be fixed now

**Closed by tomasMizera** 2023-10-26 07:49 UTC
Labels: bug, iOS, android 🤖, data corruption - sync failure - crash, recording
