### ISSUE TITLE
Position variables not updated when editing a point

### ISSUE THREAD

**Issue by ghillert** [MerginMaps/input#1756] opened 2021-11-16 22:35 UTC
I have created a simple form to capture [position variables](https://help.inputapp.io/howto/position_variables) such as `@position_altitude`, `@position_horizontal_accuracy` and `@position_vertical_accuracy`. 

![image](https://user-images.githubusercontent.com/685363/142075601-f99ebb09-7b4d-4fc2-b60b-5755acf5d360.png)

When I "Record" a new point, everything works and the form is filled with the expected values. However, when I use the "Edit Feature" and edit a geometry, the fields are cleared out and there seems to be no way to populate the fields with updated values:

![image](https://user-images.githubusercontent.com/685363/142076787-911d1ec6-d4cc-4964-89f5-5d9d1884fd50.png)

Just for comparison, if I use a simple expression like `second( now() )`, to populate a "seconds" field, the field is populated/updated as expected but this does not seem to work for position variables.

Not sure if this might be related to https://github.com/lutraconsulting/input/issues/1743

**Comment by saberraz** [comment] 2021-11-17 04:48
How about removing the option for **Apply default value on update**?

**Comment by ghillert** [comment] 2021-11-17 08:29
With `Apply default value on update` unchecked, the behavior is expected (but not what I want):

- When adding a point / geometry, the fields are populated
- When editing a point (`Edit geometry`), the old values stay present and are not cleared

My understanding is that `Apply default value on update` should be checked to get updated values when editing a geometry. Instead the values are cleared out.

**Comment by tomasMizera** [comment] 2021-11-18 07:48
Related/duplicate of  #1416

**Comment by jancelin** [comment] 2021-11-22 10:35
Hi,
when a new entity is created the @position_latitude,..., for example, is not filled in.
You have to cancel and create a new one and then it's ok

https://user-images.githubusercontent.com/6421175/142846131-68d95d1f-5423-4d0d-8714-45a1b02d7fba.mp4

.

**Comment by ghillert** [comment] 2021-11-24 20:14
I have the need to sometimes update the position of points but cannot delete (recreate) the point, as it contains all my other meta data. The issue is that for some rough measurements in the garden (Keeping track of plants 🙂), I do just use my cell phone but may later go back into the field to retake the measurement with my fancy GNSS device. Thus, I am using the accuracy value as rough guidance to identify the data points in need of being updated.

**Closed** 2022-12-08 09:41 UTC
Labels: bug, forms
