### ISSUE TITLE
Input defaults to another language

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1417] opened 2021-05-21 07:11 UTC
...if there is one in the system. In the example below, Input defaults to Japanese despite the fact that the first language setting is English. The work-around it to remove the other language(s).
![image](https://user-images.githubusercontent.com/2649047/119096962-1d5dea00-ba0c-11eb-9ce5-a6d4f24a10c3.png)

**Comment by saberraz** [comment] 2021-05-21 07:16
I think the issue is the type of English, in this case United States. The app should automatically pick any English instead of defaulting to the 2nd choice.

**Comment by saberraz** [comment] 2021-05-21 07:18
The work-around is to remove the 2nd language.

**Comment by sklencar** [comment] 2021-06-17 16:24
Strings from cpp classes using `tr` function seem to be using correct language (locale).
Translation function in QML `qsTr` is not working properly though. Essentially, when a device has several languages, it takes first and tries to load related translation file. If it fails, takes the next language from the list. 

Note that A) locale (and related translation file) is named according country code and sometimes with region postfix (e.g. `en-GB`); B) the translation fallback looks at the whole (country + region) code.  

As an example, lets have language setup from screenshot below. 
Even though Input has some Portuguese, English or Croatian translations, those will be ignored (not matching region code) and eventually Japanese is applied.

Generating and including translation files with region code  **resolves** the issue. However, its not ideal.
Would be better to change fallback in a way that if there is no marching `country+region.ts` file, it tries to load country.ts file first and only after this would fail, it will take the next language from the list?

![Screenshot_20210617-170437](https://user-images.githubusercontent.com/6735606/122434620-8f880700-cf97-11eb-8592-d1d87a752f4f.png)

**Comment by sklencar** [comment] 2021-06-18 08:18
Probably better solution is to upgrade QT - it seems that they have changed how languages are ordered.

From QT 5.15 they have changed behaviour of the fallback that it tries to truncate country code before trying to load the next language from the list.
It seems that such fix has been done here:
[https://github.com/qt/qtbase/commit/8df2bf04917e742470bbd1ff69e003811c5975ff](https://github.com/qt/qtbase/commit/8df2bf04917e742470bbd1ff69e003811c5975ff) 

Here are [docs](https://doc.qt.io/qt-5.14/qtranslator.html#load-1) describing behaviour of the `QTranslator::load` function (used to install translation in the app) in QT 5.14 which we use.
Either from commit reference above or [QT 5.15 docs](https://doc.qt.io/qt-5/qtranslator.html#load-1) you can see difference in order to load translation files.

However, I haven't tried it with bumped version of QT.

@PeterPetrik What do you think?

**Comment by saberraz** [comment] 2021-06-18 08:24
+1 to upgrade to QT 5.15!

**Comment by PeterPetrik** [comment] 2021-06-18 08:25
if the priority of the issue is not critical, lets update qt 5.15 in the future and let this resolve itself?

**Comment by saberraz** [comment] 2021-06-18 08:27
It is not very highly critical and can wait. I agree with @sklencar it is better to upgrade to a new QT, instead of a patch work here.

**Comment by PeterPetrik** [comment] 2023-06-01 05:38
We are already on Qt 6.x, so it would be good to remove workarounds in the code and let Qt handle the logic

**Comment by tomasMizera** [comment] 2023-09-25 12:59
Luckily this should be fixed now

**Closed by tomasMizera** 2023-09-25 12:59 UTC
Labels: bug, translation
