### ISSUE TITLE
Reevaluate attributes after geometry edit

### ISSUE THREAD

**Issue by sklencar** [MerginMaps/input#1416] opened 2021-05-20 13:19 UTC
It seems that feature's attributes are not updated after the feature's geometry is edited - this works in QGIS.
Its related to attributes with defined default value and "Apply default value on update" checked.

**Comment by tomasMizera** [comment] 2022-09-15 12:05
Duplicate of #1756

**Closed** 2022-09-15 12:04 UTC
Labels: bug, forms
