### ISSUE TITLE
Record feature problems on welcome project  'Start here!'

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1847] opened 2021-12-13 08:01 UTC
In welcome project 'Start here!', there are problems with recording new features.
In record form, some of the fields can't be set and after hitting save, feature is not visible on map canvas. 
Expectation is, that user is able to edit the fields and after saving the feature, the feature is visible on map. 

https://user-images.githubusercontent.com/83582181/145773733-d79f0809-efa5-4175-9c1a-c1f453a64afb.mp4

**Comment by mostlyAtNight** [comment] 2022-02-09 11:51
Hi Jozef,

I've just taken a look at this and I'm not sure it's a bug as such.

The _Start here!_ project is intended to function like a tour, showing the user the basic features of Input under instruction.  At the end of the tour it instructs the user to open the next tour project which covers capturing field data.

Some of the attributes are read-only as that was intended during the tour to allow less possibilities for users to _mess up_ the tour project.

Not sure what to do about this as the project is behaving as I intended it to.

**Comment by jozef-budac** [comment] 2022-02-10 06:18
I understand. The point is, that this are the first projects the users see and can try in Input. And in this projects, you can't record anything or when you record something, it doesn't show up. It looks like the app is broken.
This problem has been pointed out by Saber, so you can also discuss with him, how to proceed here.

**Comment by mostlyAtNight** [comment] 2022-02-10 08:06
That makes sense and I'll take a look and see if I can improve things.

**Comment by PeterPetrik** [comment] 2023-10-10 15:01
We need to rewamp whole demo project/onboarding , probably not using demo projects but custom onboarding session in the app. closing this for now

**Closed by PeterPetrik** 2023-10-10 15:01 UTC
Labels: bug
