### ISSUE TITLE
App crashing when trying to add a point to a layer without CRS

### ISSUE THREAD

**Issue by andrewroylaws** [MerginMaps/input#2450] opened 2022-12-06 01:36 UTC
Hello, this is an issue I resolved in my project and wanted to share the solution for others. I am running Mergin Maps on iOS and while try to record new features for a point layer, the app would immediately crash.

Layer: Point layer with a relation to a table layer for monitoring (think hydrant reports)

Attempted fixes that didn't work:
- reinstalling Mergin Maps
- removing relation between layer and table and resyncing project/recreating Mergin project
- removing layer and adding layer back to QGIS and resyncing project/recreating Mergin project
- resetting form for layer and resyncing project/recreating Mergin project

While reviewing other issues, #1959 caught my eye. So, I looked through my geopackage and several layers had an "undefined crs". I used the `Assign projection` tool to assign the correct projection to these layers, **including the layer that caused the app to crash which QGIS showed had no CRS**. So, it now works well.

**Comment by saberraz** [comment] 2022-12-06 07:04
This is still a bug and a layer with no CRS should not crash the app.

**Comment by tomasMizera** [comment] 2022-12-06 07:54
Hello @andrewroylaws , thanks for sharing the bug and the solution with us! 
Related to https://github.com/MerginMaps/input/issues/2362 ( <--- when project has no CRS set )

**Comment by PeterPetrik** [comment] 2023-09-27 14:31
@andrewroylaws any change you still have the project and can share with me?

**Comment by andrewroylaws** [comment] 2023-09-30 19:25
@PeterPetrik I'm afraid I no longer have access to this project.

**Comment by PeterPetrik** [comment] 2023-10-01 14:15
Ok, lets close it as not reproducible anymore - I cannot reproduce it either on my projects on iOS

**Closed by PeterPetrik** 2023-10-01 14:15 UTC
Labels: bug, iOS, data corruption - sync failure - crash, recording
