### ISSUE TITLE
Buttons in standard dialogs (yes/no, ok/cancel) are not translated

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/input#2416] opened 2022-11-30 12:19 UTC
Currently the buttons in message dialogs are not getting translated

https://stackoverflow.com/questions/31725995/how-to-translate-default-qstr-fields-e-g-messagedialog-yes-no-buttons

**Comment by tomasMizera** [comment] 2022-11-30 12:38
duplicate of #2024

**Closed by tomasMizera** 2022-11-30 12:38 UTC
Labels: bug, ui/ux, translation
