### ISSUE TITLE
Slow download of the projects

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2802] opened 2023-09-25 13:10 UTC
I am on the same network and downloading a project from the app takes much longer compared with the plugin.

**Comment by tomasMizera** [comment] 2023-09-25 13:24
Related to #330

**Comment by PeterPetrik** [comment] 2023-10-06 06:33
after https://github.com/MerginMaps/input/pull/2820 is merged, I believe this is duplicate of https://github.com/MerginMaps/input/issues/330

closing

**Closed by PeterPetrik** 2023-10-06 06:33 UTC
Labels: performance
