### ISSUE TITLE
Adding multiple entries into field with value relation widget causes app to ask the user to edit geometry of parent feature

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/input#2617] opened 2023-03-09 14:51 UTC
The situation is like this:
I create spatial parent layer, nonspatial child layer with 3 fields and one more nonspatial layer containing 3 fields with values.
I set relation between parent-child layer and for child layer's 3 fields I set their widgets to value relations, where each field corresponds to 1 field in the other nonspatial layer. Multiple selections is allowed.

Strange behavior:
In input when you create feature and within the child layer's form add values from the other table, manipulation with the second field makes the app to show the map window and edit the geometry (the one from parent layer that isn't even saved yet).

This ticket was created due to https://support.lutraconsulting.co.uk/a/tickets/1971 and testing project was also created (support/value_relation_test) and the issue replicated.

**Comment by stevenjh** [comment] 2023-05-08 09:22
I've come across this same issue and identified the issue is in the related forms, but is more prominent and unavoidable in the multi-select form.

Tests to demo the issues:

1. Bringing up the edit geometry interface
    -  Click a feature
    -  Open a child edit form (you see 'Cancel' top left, 'Save' top right, a solid green bar along the bottom with no buttons in it)
    -  Click the middle of the green bar
    -  Be taken to the feature editing interface of the parent feature.
    -  The reason this issues comes up from the multi-selects is that the 'Done' button generally maps to the same screen space as the 'Edit geometry' button. The 'Delete' and 'Advanced' buttons can also be accessed from both the child form and the multi-select UI
 2. Accessing parent feature date picker from child form
    -  click a feature
    -  Open a child edit form (with a date picker visible on the screen)
    -  Within the child form,  click in the form around where the parent date picker was
    -  Result: Date picker with date from parent feature will open.

Please let me know if you need screenshots to help explain these issues

**Comment by tomasMizera** [comment] 2023-05-08 09:31
#Related / duplicate of #2637

**Comment by stevenjh** [comment] 2023-06-27 04:29
Confirming I've got users reporting these same "1. Issue: Bringing up the edit geometry interface" issues still on Android.
I though this was resolved.

**Closed** 2023-10-05 13:42 UTC
Labels: bug
